# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: java version
        run: java -version
      - name: maven version
        run: mvn -version
      - name: docker version
        run: dockerv
         curl -v -u admin:admin -T /home/runner/work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.0-SNAPSHOT.war'ec2-15-206-81-17.ap-south-1.compute.amazonaws.com:8080/manager/text/deploy?path=/github_action_spring'
